TSDB_USERNAME = "postgres"
TSDB_LOCAL_PASSWORD = "password"
TSDB_AWS_PASSWORD = ""
TSDB_LOCAL_HOST = "localhost"
TSDB_AWS_HOST = "ec2-18-191-110-47.us-east-2.compute.amazonaws.com"
TSDB_PORT = "5432"
TSDB_DATABASE = "stonks"